### PR TITLE
Fixed an issue with an additional slash preceeding auth token causing…

### PR DESCRIPTION
**Pull request by JamesrenaudMitel**
… 401's on login

See issue #20

### CODE REVIEW

**Comment by JamesrenaudMitel** [comment]
Hmm in retrospect line 96 might not have been affected which is why those tests are failing.

**Comment by JamesrenaudMitel** [comment]
Closing PR, this was actually user error on my part.

**Comment by skaughtx0r** [comment]
Why is this closed and not merged? This fixes the error I'm having with a private registry.

**Comment by JamesrenaudMitel** [comment]
When I fixed this it actually caused more problems around the formatting of the connection string, or at least it did in my case so I backed it off instead of pushing it for merging. I also never received feedback from the repository maintainer on any issues raised so I fear this is a dead package.

**Comment by skaughtx0r** [comment]
Interesting, I ended up just using your fork as it appeared to fix the trailing slashes for me.

**Pull request closed without merging**
